GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJzeWFoYW4iLCJlbWFpbCI6InN5YWhhbkBnbWFpbC5jb20iLCJpYXQiOjE2ODY2NTUyODAsImV4cCI6MTY4NjY1NTMxMH0.8KGnyL-LYzCwkTkwi-jMNYyZMr3NplqIr6mGnwJyohs

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "syahan",
    "email": "syahan@gmail.com",
    "password": "qwe123qwe",
    "confPassword": "qwe123qwe"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "syahan@gmail.com",
    "password": "qwe123qwe"
}

###
GET http://localhost:3000/token



###
DELETE http://localhost:3000/logout
